apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook
  annotations:
    cert-manager.io/inject-apiserver-ca: "true"

webhooks:
- name: webhook.default.svc.cluster.local
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
  clientConfig:
    # service:
    #   namespace: default
    #   name: webhook
    #   path: /mutate
    url: https://webhook-default.apps.mkovarik.test.redhat.com/mutate
  rules:
  - operations: ["CREATE"]
    apiGroups: ["tekton.dev"]
    apiVersions: ["*"]
    resources: ["pipelineruns"]
    scope: "*"